#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr
nitrogen --restore
compton -b
$HOME/.scripts/launch_polybar.sh
redshift &

bspc monitor -d term web code file media extra

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#81A1C1

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
